name: C# Console Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build and Run
      run: |
        dotnet new console -o tempApp
        mv HelloWorld.cs tempApp/Program.cs
        cd tempApp
        dotnet run
