name: Run
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run:
    name: Run
    runs-on: windows-2022
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and Run
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
        DOTNET_GENERATE_ASPNET_CERTIFICATE: false
        DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true
      shell: pwsh
      run: |
        dotnet Prebuilt/HelloWorld.dll
