name: C# Console Application
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build-and-run:
    runs-on: windows-2022
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and Run
      run: |
        dotnet new console -o tempApp
        mv HelloWorld.cs tempApp/Program.cs
        cd tempApp
        dotnet run
