name: Run
on:
  workflow_dispatch:
jobs:
  run:
    name: Run
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: 'windows-latest'
          - runner: 'ubuntu-latest'
          - runner: 'macos-latest'
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Run
      run: |
        curl -sLO https://github.com/jdpurcell/dotnet-ci-test/releases/download/latest/HelloWorld.zip
        unzip -q HelloWorld.zip -d HelloWorld
        dotnet HelloWorld/HelloWorld.dll
